version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "
      python manage.py makemigrations parkprice parkspot
      && python manage.py migrate
      && python manage.py load_intial_data
      && python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - 5000:8000
    volumes:
    - .:/app