# Generated by Django 3.2.9 on 2021-11-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.TextField(blank=True, db_column='days', null=True)),
                ('times', models.TextField(blank=True, db_column='times', null=True)),
                ('tz', models.TextField(blank=True, db_column='tz', null=True)),
                ('price', models.IntegerField(blank=True, db_column='price', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'RateInfo',
                'managed': True,
            },
        ),
    ]
